# Generated by Django 6.0 on 2026-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_producttag_title_az_producttag_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
